
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx/www:/data/www
  
  flight:
    build: ./flight_info
  
  chat:
    build: ./chatbot
